CREATE DATABASE SALES_DB;

USE SALES_DB;

CREATE TABLE SALES (
    ORDER_ID INT(12) NOT NULL,
    QTY_ORDERED INT(100),
    PRICE_PER DECIMAL(6,2),
    SALES DECIMAL(12,2),
    ORDER_DATE DATE
);

CREATE TABLE SALES_SUM (
    SALES_TOTAL_ID INT AUTO_INCREMENT,
    SALES_TOTAL DECIMAL(10,2),
    PRIMARY KEY (SALES_TOTAL_ID)
)

insert into SALES_SUM (SALES_TOTAL) values (4211.20);
commit;